// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrNSnTC-sOu-sHctSOIz1KpF8UwfcPFnE',
    appId: '1:301552848913:web:d1c91bc094c9e87823e1b0',
    messagingSenderId: '301552848913',
    projectId: 'findit-c3521',
    authDomain: 'findit-c3521.firebaseapp.com',
    storageBucket: 'findit-c3521.firebasestorage.app',
    measurementId: 'G-DK3WMENNRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_a8YCrOLKkfIdyaTjqISOcPf0JMiNQY',
    appId: '1:301552848913:android:ca3de7acf4898ae223e1b0',
    messagingSenderId: '301552848913',
    projectId: 'findit-c3521',
    storageBucket: 'findit-c3521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuEhafRRJzv0fRQp1ZS9TA72sD1eMnOSQ',
    appId: '1:301552848913:ios:20e65660ba82834d23e1b0',
    messagingSenderId: '301552848913',
    projectId: 'findit-c3521',
    storageBucket: 'findit-c3521.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuEhafRRJzv0fRQp1ZS9TA72sD1eMnOSQ',
    appId: '1:301552848913:ios:20e65660ba82834d23e1b0',
    messagingSenderId: '301552848913',
    projectId: 'findit-c3521',
    storageBucket: 'findit-c3521.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrNSnTC-sOu-sHctSOIz1KpF8UwfcPFnE',
    appId: '1:301552848913:web:a35f0a9c0f2dcaae23e1b0',
    messagingSenderId: '301552848913',
    projectId: 'findit-c3521',
    authDomain: 'findit-c3521.firebaseapp.com',
    storageBucket: 'findit-c3521.firebasestorage.app',
    measurementId: 'G-Y7EM7NMXLC',
  );
}
